### ISSUE TITLE
Different constrains per cluster

### ISSUE THREAD

**Issue by kennylajara** [joshlk/k-means-constrained#15]
Is there a way to have a different constrains for different clusters? Like: I wan three clusters, one with a maximum of 6 points and 2 with a maximum or 4.

**Comment by joshlk** [comment]
Hi @kennylajara, thanks for the message. Unfortunately you can't define different constraints for each centroid. If you wanted to hack the code I would have a look at how the [min-cost-flow graph is constructed](https://github.com/joshlk/k-means-constrained/blob/eda40741431286a71bff72c59077287d1376fd31/k_means_constrained/k_means_constrained_.py#L417) and modify that function. You could then provided different constraints for each centroid. Good luck 😃
