### ISSUE TITLE
Possible to specify custom distance matrix?

### ISSUE THREAD

**Issue by amks1** [joshlk/k-means-constrained#17]
Is it possible with this implementation to cluster using a custom distance matrix?

**Comment by joshlk** [comment]
No it does not. But if you want to hack your own solution you can try changing this line: https://github.com/joshlk/k-means-constrained/blob/eda40741431286a71bff72c59077287d1376fd31/k_means_constrained/k_means_constrained_.py#L402

**Comment by amks1** [comment]
Thanks. Sorry if this is a dumb question, but are the cluster centers chosen from the set of input points?

**Comment by bibblybobblyben** [comment]
Hi - thanks for your work building this package. I have also come across the question of trying to implement a custom distance metric in the clustering so have opened a PR to address it. Happy to be corrected if this is not a desirable change in the main package.

**Comment by Ivan-Tucker** [comment]
Is this issue closed because it will be included in an upcoming release or for another reason?
