### ISSUE TITLE
Fitting times for KMeansConstrained is much longer than regular KMeans()

### ISSUE THREAD

**Issue by jack11wagner** [joshlk/k-means-constrained#22]
Is this supposed to be taking much longer than regular KMeans() to fit to data?

**Comment by joshlk** [comment]
Hi, yes - it takes longer as the algorithm is much more complex. I would recommend trying it with a small sample and then trying bigger and bigger samples to get an idea what the runtime would be

**Comment by jack11wagner** [comment]
Thanks!
