### ISSUE TITLE
Import Error [BUG]

### ISSUE THREAD

**Issue by ekwan** [joshlk/k-means-constrained#23]
Hi, I'm getting this error with Python 3.9.5 and numpy 1.22.3:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/6035106/163594218-921e4f61-81da-4c48-b7c7-c2fa746de433.png">

**Comment by DedaFab** [comment]
Same error, you need to install the numpy version 1.22.0.
The further problem is when another package requires to install another version of numpy, then you need to reinstall again that version 1.22.0 of numpy.

**Comment by joshlk** [comment]
The issue should be resolved with the latest version. Please update the package using `pip install 'k-means-constrained>=0.7.2'` and report back

**Comment by ekwan** [comment]
Tried it and it seemed to work, though it took a while to load.  Thanks for fixing it!

**Comment by joshlk** [comment]
Great!
