### ISSUE TITLE
Feature value constrained in a spatial aplication 

### ISSUE THREAD

**Issue by orlandoandradeb** [joshlk/k-means-constrained#26]
Hello everyone !

Is it possible to add a second constrained related with the sum of attributes of each features?

Best regards, 
Orlando

**Comment by joshlk** [comment]
Yes it algorithmic in principle could support it but this package doesn’t and doesn’t plan to.

Feel free to ask questions about the code if you would like to make these modifications yourself.

**Comment by joshlk** [comment]
I'm closing this for now. Re-open the ticket and leave a comment if you are still looking at this and wasnt more assistance.
