### ISSUE TITLE
[BUG] Incompatible with `ortools >= 9.4` (`No module named 'ortools.graph.pywrapgraph'`)

### ISSUE THREAD

**Issue by esmail** [joshlk/k-means-constrained#28]
**Describe the bug**
`k-means-constrained` is incompatible with `ortools` version 9.4+

**Minimum working example**
`from k_means_constrained import KMeansConstrained`

Results in:
```
...
    from k_means_constrained import KMeansConstrained
  File "/home/ubuntu/hbx/python/lib/python3.8/site-packages/k_means_constrained/__init__.py", line 4, in <module>
    from .k_means_constrained_ import KMeansConstrained
  File "/home/ubuntu/hbx/python/lib/python3.8/site-packages/k_means_constrained/k_means_constrained_.py", line 29, in <module>
    from k_means_constrained.mincostflow_vectorized import SimpleMinCostFlowVectorized
  File "/home/ubuntu/hbx/python/lib/python3.8/site-packages/k_means_constrained/mincostflow_vectorized.py", line 4, in <module>
    from ortools.graph.pywrapgraph import SimpleMinCostFlow
ModuleNotFoundError: No module named 'ortools.graph.pywrapgraph'
```

**Versions:**
- Python: Python 3.8.10
- Operating system: Linux
- k-means-constrained: k-means-constrained==0.5.1
- numpy: numpy==1.23.1
- scipy: scipy==1.8.1
- ortools: **ortools==9.4.1874**
- joblib: joblib==1.1.0
- cython (if installed):

**Comment by lperron** [comment]
Please replace `ortools.graph.pywrapgraph` by  `ortools.graph.python.min_cost_flow`.

**Comment by lperron** [comment]
The good news is that it now supports numpy to speed-up the creation of the graph.

See this [example](https://github.com/google/or-tools/blob/stable/ortools/graph/samples/simple_min_cost_flow_program.py).

**Comment by datatravelgit** [comment]
> Please replace `ortools.graph.pywrapgraph` by `ortools.graph.python.min_cost_flow`.

As far as I my test goes, this is not sufficient. Other imports may need to be changed to adapt to or tools >=9.4

**Comment by lperron** [comment]
Pywrapgraph has be split in 3.
It should be easy to check it's occurrences

Le lun. 29 août 2022, 12:26, Data Travel ***@***.***> a
écrit :

**Comment by joshlk** [comment]
The issue should be resolved with the latest version. Please update the package using `pip install 'k-means-constrained>=0.7.2'` and report back

**Comment by joshlk** [comment]
Great. I’ll close this for now. Let me know if you have any more issues

**Comment by datatravelgit** [comment]
Just tested. All ok on my side as well. Thanks

**Comment by lperron** [comment]
Thanks for the rapid fix.
