### ISSUE TITLE
Microsoft Visual C++is required

### ISSUE THREAD

**Issue by meteve** [joshlk/k-means-constrained#3]
Hello,
When installing k-means-constrained, I get the error: "Microsoft Visual C++ 14.0 is required."
Do you know if the Redistribuable Visual C++ package is sufficient or do we need the whole Microsoft Visual?
Thank you!

**Comment by joshlk** [comment]
Hi, I think you need to install the Visual c++ build tools. You can download it here: https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by meteve** [comment]
Thanks a lot!
