### ISSUE TITLE
facing the issue during running 

### ISSUE THREAD

**Issue by nsitlokeshjain** [joshlk/k-means-constrained#31]
found the following error:

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by joshlk** [comment]
The issue should be resolved with the latest version. Please update the package using `pip install 'k-means-constrained>=0.7.2'` and report back

**Comment by joshlk** [comment]
I'm closing this for now. Let me know if you require more assistance
