### ISSUE TITLE
Wrong clustering

### ISSUE THREAD

**Issue by mosikh** [joshlk/k-means-constrained#34]
Hello,
I have a bunch of house points. I have extended a line which extends Glass fiber to each house. 
Now, I'd like to cluster the points to assign a distributor to each cluster. The maximum of house points per cluster should be 20.
I calculated an adjacency matrix based on the Glass fiber line for the data set which has 61 points, here as an example. I do the clustering by this library and the pre-computed adjacency matrix. However, I sometimes see a wrong clustering, which is observable in the picture. 

It is my code:
"**am**" is the adjacency matrix of distances
db = KMeansConstrained(n_clusters = 4,size_max=20, random_state=0) 
result = db.fit_predict(am)

In the picture, the black line is the glass fiber line which is the base of calculation and the colorful points are the my clustered points by the algorithm. The green and yellow clusters are not in the best state, as you see. 
I have [sometimes](url) the same issue with other datasets, as well. 

![kmeans constrained](https://user-images.githubusercontent.com/46829370/189359628-4ad9ec79-6c09-4260-a357-ea81a735d832.jpeg)

I appreciate any help to improve the result. 

**Versions:**
- Python: 3.9
- Operating system: Windows
- k-means-constrained: 0.7.2
- numpy: 1.23.2
- scipy: 1.9.1
- ortools: 9.4.1874
- joblib: 1.1.0
- cython (if installed): is not installed

Best regards,
Mostafa

**Comment by joshlk** [comment]
You need to provide a minimum, reproducing example otherwise it’s not possible to debug this issue. Closing ticket until more information is provided.
