### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by manamhr** [joshlk/k-means-constrained#37]
**Describe the bug**

While importing the library, this error happens:
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
so I did following command to downgrade numpy and install k_means_constrained again:

**Minimum working example**
Code and minimum data to reproduce the error. The example should be copy and pastable to reproduce the problem:
 from k_means_constrained import KMeansConstrained

**Versions:**
- Python: 3.9.7
- Operating system: [MacOS]
- k-means-constrained: 0.7.2
- numpy:1.23.4
- scipy:1.7.3
- ortools:9.4.1874
- joblib:1.1.0
- cython (if installed):0.29.24

I installed k_means_constrained which upgraded numpy to 1.23.4 and when importing k_means_constrained created

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
so I did following command to downgrade numpy and install k_means_constrained again:

!pip uninstall numpy -y
!conda install -y -c conda-forge numpy 
!pip uninstall k_means_constrained -y
!pip install k_means_constrained --no-binary k_means_constrained
right now I have k-means-constrained-0.7.2, numpy to 1.23.4 and still same error. even changed to k-means-constrained-0.7.0 and numpy to 1.21.5 still same error I have this issue on my Apple M1 pro, Anaconda environment, Python 3.9.7. 
Any advice?

**Comment by kellyvos** [comment]
I'm getting the same error, how did you solve the problem?

**Comment by joshlk** [comment]
Hi @kellyvos, can you please provide the numpy, k-means-constrained and Python version you are using?

**Comment by kellyvos** [comment]
> Hi @kellyvos, can you please provide the numpy, k-means-constrained and Python version you are using?

I'm sorry I made a mistake
