### ISSUE TITLE
Possibility to use this on k-modes

### ISSUE THREAD

**Issue by Jhellewaard** [joshlk/k-means-constrained#42]
I want to use exactly the constrained clusters, as this package offers, since I'd like to create equal-sized clusters.

However, I'm working with categorical data. Is there also a k-modes (or k-prototype) alternative for this algorithm?

**Comment by joshlk** [comment]
Hi @Jhellewaard,

Nice to meet you 👋 

I would recommend converting categorical features into one-hot features if you would like to use categorical data - for example use [sklearn.preprocessing.OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html).

A combined datasets of one-hot features with continuous data can be tricky for k-means sometimes. You may need to categorise all your features to get it to work. For example by binning the data into intervals and you can use [sklearn.preprocessing.KBinsDiscretizer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.KBinsDiscretizer.html) to do that.

I hope that helps,
Josh

**Comment by joshlk** [comment]
I am closing this thread due to inactivity
