### ISSUE TITLE
Weighting observations

### ISSUE THREAD

**Issue by RobShaw77** [joshlk/k-means-constrained#49]
As far as I can tell, it is not currently possible to give weights to observations. One obvious workaround is to duplicate points but this would be very inefficient. Has this been considered as a future development?

In my example, I have a series of places that I'm clustered and would like to take account of their population in the max min cluster sizes.

Thanks
Rob

**Comment by joshlk** [comment]
Hi, thanks for your interest. Have a look at this thread: https://github.com/joshlk/k-means-constrained/issues/24. There is no currently no work being done on this, but I am happy to take contributions to the repo :)
