### ISSUE TITLE
Issue with min cost flow input

### ISSUE THREAD

**Issue by gregmorse** [joshlk/k-means-constrained#51]
I'm receiving the following error when calling KMeansConstrained.predict():

"There was an issue with the min cost flow input."

This model contains 5 clusters and is running on 850 data points.  During training, I have set the min and max size to be 140 and 200 respectively.  If I relax the size constraint to 120, 220, predict() works fine.

**Comment by joshlk** [comment]
Hi 👋,

Can you please provided a minimum workable example to demonstrate the issue. [Stackoverflow have a good article on how to produce this](https://stackoverflow.com/help/minimal-reproducible-example). Importantly the example should contain the least amount of code and data to reproduce the error. Ideally you should be able to paste it as few lines of code and include only a few datapoints of data within a GitHub comment.

Could you also include the k-means-constrained version you are using.

Thanks,
Josh

**Comment by joshlk** [comment]
I'm going to close this as I haven't received a response. Please reopen it if you wish
