### ISSUE TITLE
Is it possible to implement MiniBatchKmeansConstrained?

### ISSUE THREAD

**Issue by pengzhenghao** [joshlk/k-means-constrained#54]
My dataset is too large that it takes very long time to converge. Do you have any suggestion for my usecase? Thanks!

**Comment by joshlk** [comment]
I would suggest pre-segmenting that data. For example, if each row is a person, segment on gender or location. Or you can use normal K-Means first to get big cluster and then use KMeansConstrained to get smaller ones
